
##### RETRIEVING #####

### Retrieve users
GET http://localhost:8080/users

### Retrieve items
GET http://localhost:8080/items


### Retrieve filtered items
GET http://localhost:8080/item-search/stone

### Retrieve orders
GET http://localhost:8080/orders


##### ADDING #####

### Adding a user
POST http://localhost:8080/create-user
Content-Type: application/json

{
    "firstName": "mbhdj",
    "lastName": "scsc",
    "email": "cscgg",
    "password": "cscsc",
    "address": "Hedinsgatan 3",
    "city": "Stockholm",
    "postcode": 11223,
    "cart": [],
    "isStaff": true
}

### Adding an item
POST http://localhost:8080/items
Content-Type: application/json

{
    "_id": "00002",
    "title": "Wingspan",
    "image": "https://www.dragonslair.se/images/53575/product",
    "publisher": "Stonemaier Games",
    "price": 697.00,
    "numInStock": 22,
    "isExpansion": false,
    "releaseYear": 2019,
    "minPlayers": 1,
    "maxPlayers": 5
}

### Adding an order
POST http://localhost:8080/orders
Content-Type: application/json

{
    "_id": "12212122",
    "userId": 1,
    "orderDate": "J.A@thefriendzone.com",
    "packagedDate": "iheartpaleontologists",
    "shippedDate": "Hedinsgatan 3",
    "deliveredDate": "Stockholm",
    "contents": [{"_id": 123, "quantity": 2}, {"_id":567, "quantity": 8}, {"_id": 155, "quantity": 1}, {"_id": 321, "quantity": 2}, {"_id": 111, "quantity": 6}, {"_id": 453, "quantity": 3}, {"_id": 789, "quantity": 1}, {"_id": 341, "quantity": 7}],
    "totalCost": 9876.00
}





### Deleting a user
DELETE http://localhost:8080/users/ID

### Replace a user's attributes
PUT http://localhost:8080/users/ID
Content-Type: application/json

{
    "status": "deceased"
}

### Update a user
PATCH http://localhost:8080/users/ID
Content-Type: application/json

{
    "password": "iHATEpaleontologists"
}